# Generated by Django 5.0.1 on 2024-02-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_comment_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',)},
        ),
    ]
