# Generated by Django 5.0.1 on 2024-03-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
